[tool.poetry]
name = "hw-10"
version = "0.1.0"
description = ""
authors = ["Alex Nikiforov <alex.kifir95@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
